### ISSUE TITLE
v0.2.4 dogfood remarks

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#16]
I love dogfooding this software :dancer: Feel free to take these things I noticed as you see fit and they're very much open for discussion. :hugs: 

- After creating a module (both profile and content) and printing the `dat.json` file, there's a buffer as value for the `url` name?

```
{
  "title": "Chris Hartgerink",
  "description": "Meta-researcher",
  "url": {
    "type": "Buffer",
    "data": [
      240,
      214,
      196,
      217,
      34,
      85,
      11,
      159,
      144,
      113,
      95,
      177,
      165,
      25,
      143,
      127,
      126,
      85,
      90,
      211,
      130,
      219,
      81,
      190,
      32,
      215,
      75,
      185,
      60,
      77,
      221,
      133
    ]
  },
  "main": "",
  "license": "https://creativecommons.org/publicdomain/zero/1.0/legalcode",
  "subtype": "profile",
  "type": "profile",
  "follows": [],
  "contents": []
}
```

- The license is also included in the profile. That is not necessary in the spec, but we could add it? What are your thoughts?

- When I'm trying to update profile metadata, it reads `Title` instead of `Name`

- When I'm trying to update profile metadata, I cannot leave `Title` blank but can leave `Description` blank (updating content metadata I can leave the `Title` blank as well).

- A `prompts select` menu for *opening a module* in the file explorer for the interactive menu, maybe?

- A `prompts select` menu for *showing a module* path for the interactive menu, maybe?

- When I open a module's folder, I see this structure (for example):

```
├── 80
│   └──....
├── .dat
│   ├── ...
├── dat.json
└── default
    ├── ...
```

I understand the `.dat/` and `dat.json`, but the `default/` and `80/` I don't? Maybe this is more for the SDK?
- I cannot pipe output of the `hypergraph path <hash> | ls` due to async, I think?

**Comment by dpaez** [comment]
Hi all 👋 
I have some comments, regarding the first question (url as buffer), we are indeed storing the dat key as a buffer which is the raw representation, the usual hash we see its the hexadecimal representation. So I decided to store it as bytes (buffer) and whenever we need to display it we can do the `.toString('hex')`. My rationale behind this was that some dat internals parts would benefit from have to deal with the raw buffers. I can update the spec if needed or we can move the issue to the sdk for discussion. 👍 

My other comment is about the penultimate item, we can open an issue on the sdk for this. Corestore is creating folders like `xy/` and those should be inside the `.dat` so there is something I need to check.

:v:

**Comment by juliangruber** [comment]
> * After creating a module (both profile and content) and printing the `dat.json` file, there's a buffer as value for the `url` name?

This is how the sdk currently works and has nothing to do with the cli. I opened an issue here: https://github.com/p2pcommons/sdk-js/issues/16.

> * The license is also included in the profile. That is not necessary in the spec, but we could add it? What are your thoughts?

Better to be more explicit imo, otherwise if some person finds the folder how are they going to know what the license is? Alternatively, we could also link to the spec instead, which would be even more self descriptive. 

> * When I'm trying to update profile metadata, it reads `Title` instead of `Name`

Good catch! The fix will come in the next release.

> * When I'm trying to update profile metadata, I cannot leave `Title` blank but can leave `Description` blank (updating content metadata I can leave the `Title` blank as well).

Are you using the prompt? You're not leaving them blank, it's still using the default values. Could it be that the color scheme hides these from you?

Using the non-prompt version this was a bug and will be fixed in the next release.

> * A `prompts select` menu for _opening a module_ in the file explorer for the interactive menu, maybe?

Makes perfect sense! Next release 🚢 

> I understand the `.dat/` and `dat.json`, but the `default/` and `80/` I don't? Maybe this is more for the SDK?

Yes this is a Diego question 🌝 

> * I cannot pipe output of the `hypergraph path <hash> | ls` due to async, I think?

Try this:

```bash
$ ls `hypergraph path <hash>`
```

**Comment by juliangruber** [comment]
This issue now lives in:

- https://github.com/p2pcommons/sdk-js/issues/16
- https://github.com/p2pcommons/sdk-js/issues/17
- https://github.com/p2pcommons/specs/issues/7
