### ISSUE TITLE
Wikidata identifiers for `subtype`

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#20]
Currently, we're defaulting to producing `subtype: 'content'` (or `subtype: 'profile'`) for the `type: content` (or `type: 'profile'`). 

The end goal is to have more informative subtypes, and WikiData is the ideal one IMO. I will collect a list of subtypes that would make sense for the first usage. I previously wrote a bit about this [here](https://talk.libscie.org/t/potential-for-wikidata-in-creating-and-consuming-content/11/3?u=chjh). A start could be:

| Name       | WikiData ID |
|------------|-------------|
| Theory     | Q17737      |
| Hypothesis | Q41719      |
| Prediction | Q748250     |
| Design     | Q82604      |
| Methodology | Q185698     |
| Equipment | Q16798631 |
| Data       | Q42848      |
| Analysis   | Q217602     |
| Results    |  ???           |
| Discussion | Q3030248    |
| Abstract   | Q333291     |
| Other      | Q55107540   |

I'm being very verbose by including the category 'Other' for ease of use right now. This would be for `type: content` specifically.

Another cool aspect is that for a profile, quite some people already have identifiers due to the [Wikicite project](https://meta.wikimedia.org/wiki/WikiCite). Mine, for example, is [`Q28922414`](https://www.wikidata.org/wiki/Q28922414). This would be a direct prompt for the identifier, because there are too many people in WikiData to have in a list right now :)

WikiData could provide us as a stable base for identifying modules 🎊

**Comment by juliangruber** [comment]
Currently blocked by https://github.com/p2pcommons/sdk-js/issues/22.

**Comment by juliangruber** [comment]
@chartgerink what should actually be stored, the subtype's name, the wikidata id, or both maybe?

**Comment by chartgerink** [comment]
How would you think both could look like? I was initially thinking just the wikidata id, because that's stable and unambiguous.

**Comment by juliangruber** [comment]
We could join the strings like `Q217602 (Analysis)`? Or we could just store the ID and use our tooling to print the nice name, yeah I think that'll work better.

Why is the id for `Results` `???`?

**Comment by chartgerink** [comment]
Okay, then let's do the id in the subtype and have a pretty print wrapper for those we prespecify.

There's no wikidata entry for results specifically, so I left that open for now. I need to find a proper synonym to capture that. Suggestions welcome :)

**Comment by juliangruber** [comment]
Blocked by https://github.com/p2pcommons/sdk-js/issues/26
