### ISSUE TITLE
Open main file

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#44]
In dogfooding `v0.2.9` I realized that it would be nice to directly open the main file from the command line where those are present. Now I need to read the metadata, remember the main file (just in case there are multiple in the module), open the module, and double-click the main file (if I remember it correctly).

We could add `Open main file for...` or something to the action list? I would assume just the system default to open it.

**Comment by juliangruber** [comment]
Sounds good! And the action could be something like `hypergraph main <HASH>`?

**Comment by chartgerink** [comment]
Yes, that would work :)
