### ISSUE TITLE
Prompt subtype from select to autocomplete?

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#45]
The subtype selection menu now gives a [`select` prompt](https://github.com/terkelg/prompts#selectmessage-choices-initial-hint-warn), which becomes more tedious as the list becomes longer.

We might consider switching to the [`autocomplete` prompt](https://github.com/terkelg/prompts#autocompletemessage-choices-initial-suggest-limit-style) if it's not too much of a hassle? It is a bit more usable for me personally.

**Comment by juliangruber** [comment]
Sure that's a relatively easy change!

**Comment by juliangruber** [comment]
It was a one line change 🍾 and will be part of the next release.
