### ISSUE TITLE
`name` in profile metadata

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#53]
While showing the CLI to @psobrakseaton I noticed a minor issue that I'd like to post for reference.

Metadata key `title` in a `type: profile` is now called `name`.

```js
{
  "description": "",
  "url": "dat://69a65e3a6a16ece747256eae54d50187d0940d1b30b1a9fcea1a89baee3ff2f3",
  "links": {
    "license": [
      {
        "href": "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
      }
    ],
    "spec": [
      {
        "href": "https://p2pcommons.com/specs/module/0.2.0"
      }
    ]
  },
  "type": "profile",
  "subtype": "",
  "main": "against-excellence.html",
  "follows": [],
  "contents": [],
  "name": "Patch Sobrak-Seaton"
}

```

**Comment by juliangruber** [comment]
This is a bit tricky...if you read the `dat.json` from disk, it will correctly show `"title": "Patch Sobrak-Seaton"`. We're rewriting this field however in the `read` command in order not to be confusing, because everywhere else the cli calls it "Name" not "Title". It is however also unexpected for the `read` command to output json that isn't compliant with the module spec.

If you agree, I'll change the code so it returns "title" in the `read` command, to choose the lesser evil.

**Comment by juliangruber** [comment]
If we do that, what about the `read <HASH> <key>` command? Should it use "name" or "title"?

**Comment by juliangruber** [comment]
It would be great if we decide in which places a "Title" should be called a "Name" and in which it shouldn't.

**Comment by chartgerink** [comment]
Hahaha yes it is tricky! Didn't think of checking the `dat.json` directly, woops.

Yes, I concur that we should decide how to make this consistent. I think for the prompts we should make the name/title differentiation for profile/content modules, respectively. For the printouts of the `dat.json` only, I think it makes sense to not do that. 

In other words, all direct prints of `dat.json` should make *no* adjustments, all indirect ones should. What do you think?

**Comment by juliangruber** [comment]
I just realized, the `read` command actually doesn't print the `dat.json`, it lists how the sdk exposes the data. Note how there's no `"p2pcommons"` key in the output you posted above. This makes me actually question the purpose of the `read` command...I think either we make it output the `dat.json` and then of course without the name/title rename, or we make it output the representation that p2pcommons offers, and then I think it also makes sense to rename the keys.

**Comment by chartgerink** [comment]
If it is simply a support function for the other actions, I think it makes sense to drop the `read` command from being user-facing. In the end, most users will be confused by this information anyway, and if we use this solely to make presentation elsewhere easier, changing it to print the `dat.json` will only make that more difficult, no?

I trust in your decision :heart:

**Comment by juliangruber** [comment]
The `read` command isn't actually used by anything else, let's drop it :+1:

**Comment by juliangruber** [comment]
Ok dropped, I think this can be closed :)
