### ISSUE TITLE
Main file not opened and no error

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#54]
While showing the CLI to @psobrakseaton I noticed a minor issue that I'd like to post for reference.

When trying to open the main file for module (both content and profile) the file isn't opened and no error is given.

**Comment by juliangruber** [comment]
what file type were you trying to open, and on which operating system with which window manager?

**Comment by chartgerink** [comment]
👋 

sorry for not providing more info :woops: It was on Mac OS, Finder, and I tried with both HTML and PDF of various kinds.
