### ISSUE TITLE
Terminal availability upon module creation

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#59]
Whenever I create a new module, the Dat key is printed, but it takes several seconds for the terminal to become available again. Whenever I do any other actions, it's near immediate. This is not due to the `~/.p2pcommons` needing to be initialized from scratch, because it's already there. It seems to me like something is stalling at this point? If it is part of the module creation and not a performance issue, we might think about adding a progress bar about the module init process?

This happens on my trial runs on MacOS Catalina 10.15.1, for `node v12.12.0`, `hypergraph 0.2.14`.

**Comment by juliangruber** [comment]
I believe this is due to how the sdk works, cc @dpaez

**Comment by juliangruber** [comment]
We're basically waiting for the `sdk.destroy()` method to finish, after `sdk.init()`.

**Comment by juliangruber** [comment]
Good that you're ask, once I understand what's happening I can add a spinner like

`... seeding initial state` or so

**Comment by dpaez** [comment]
yeah, the `destroy` method can feel a bit slow. Adding a spinner and/or a friendlu message indicating what is happening can improve the experience. If we need to go beyond we could explore something like using a worker or so. And seeing this with different eyes, once we figured it out how to go with the daemon we'll be in a different position cause we'll only need to connect to the daemon and the daemon will handle all the networking so I guess that can improve the whole experience.

The communication can look like this:

`daemon <---> sdk <---> cli`

**Comment by juliangruber** [comment]
> Adding a spinner and/or a friendlu message indicating what is happening can improve the experience.

What do you think this message could be?

**Comment by juliangruber** [comment]
I've now added a spinner like this:

![Screenshot 2019-12-11 at 13 49 21](https://user-images.githubusercontent.com/10247/70622835-10d14180-1c1d-11ea-86bb-5d5a94e0b523.png)

**Comment by chartgerink** [comment]
Nice! We can close this then. Might revisit this at a later point if we want to increase performance.
