### ISSUE TITLE
Console logs a warning upon initialization

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/cli#6]
Whenever I initialize Hypergraph interactively, I get this warning appended to the output:

`(node:11126) ExperimentalWarning: The fs.promises API is experimental`

When I make it less interactive (e.g., `hypergraph create content`) it is prepended (? is that a word; it is before the output anyway).

**Comment by juliangruber** [comment]
What node version are you running?

**Comment by juliangruber** [comment]
I removed the `invalid` label because this is most commonly used for invalid bug reports

**Comment by chartgerink** [comment]
Node version `v10.16.0` on Linux Mint :)

**Comment by juliangruber** [comment]
Hm interesting! And which hypergraph-xyz/cli version? `hypergraph --version`

**Comment by chartgerink** [comment]
I am using hypergraph `v0.2.2` (noting these things for the issue template :+1:)

**Comment by juliangruber** [comment]
Ok I can reproduce using this particular node version :)

**Comment by juliangruber** [comment]
0.2.3
