### ISSUE TITLE
Set parent module for content module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#71]
**User story**
As a Hypergraph user
I want to define the parent module for my content module
so that the provenance is clearly defined for my work

**Workflow**
- [x] Code
- [x] Test

**Acceptance criteria**
- When creating a new module, the user is prompted to specify a parent module (if any published modules already exist)
- When updating an existing module, the user is prompted to specify a parent module (if any published modules already exist)
- Selecting a parent module is always optional
- Only published modules can be selected as a parent module

**Comment by juliangruber** [comment]
> * When creating a new module, the user is prompted to specify a parent module (if other modules already exist)

add: if other registered modules already exist.

Right, @chartgerink? Since the parent can only be a versioned module, and the only way to get versioned modules right now is to register them.

**Comment by chartgerink** [comment]
Technically we could allow non-published content to be parents if it exists locally and is valid, but it sounds like a UX nightmare to explain right now.

> p2pcommons.parents (specific to p2pcommons.type: content) MUST be an array of strings containing versioned Dat archive keys. These versioned Dat archive keys SHOULD each refer to a valid module of p2pcommons.type: content.

So I'll +1 @juliangruber and if it appears users really want to not have to publish their previous steps first, we can deal with that then.

**Comment by jameslibscie** [comment]
I've updated the specs. Nice one on the labeling @juliangruber , you're fast! :D

**Comment by juliangruber** [comment]
Blocked by https://github.com/p2pcommons/sdk-js/issues/77

**Comment by juliangruber** [comment]
> * Only published modules can be selected as a parent module

Shall we enforce this in the SDK or is this a CLI issue? For integrity's sake (and so this is prevented in Desktop too) it would be great to add this to the SDK in my opinion. cc @dpaez

**Comment by dpaez** [comment]
@juliangruber agree 💯

**Comment by jameslibscie** [comment]
@juliangruber @dpaez I agree as well. That way, the p2pcommons also enforces provenance in a way. _Starting on something new? Publish your previous work first!_ 
I will update the @p2pcommons/sdk-js/#77 issue to become a feature that also specifies that only published modules may be selected.

**Comment by jameslibscie** [comment]
p2pcommons/sdk-js#77 is closed, so this issue should no longer be blocked now.

**Comment by juliangruber** [comment]
as discussed in slack, the update hasn't been released yet

**Comment by jameslibscie** [comment]
Looks good to me!
