### ISSUE TITLE
Delete content module

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#79]
**User story**
As a Hypergraph user
I want to be able to delete my own created content modules
so that I can correct mistakes and keep my projects organised

**Workflow**
- [x] Code
- [x] Test

**Acceptance criteria**
- Delete is only possible for modules the user has write access to
- Delete only deletes the module locally and has no effect on remote copies
- The ability to delete profile modules will probably be necessary at some point, but is not top priority now. Can be included if it's little extra work.

**Comment by juliangruber** [comment]
> * The ability to delete profile modules will probably be necessary at some point, but is not top priority now. Can be included if it's little extra work

Currently there's no way to have multiple profile modules in the CLI, I think we can add that later
