### ISSUE TITLE
Flags for update consistent with create action

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#87]
**User story**
As a Hypergraph user
I want to be able to update metadata fields using the same syntax as `create`
so that I only have to remember one way of working

**Acceptance criteria**
- A syntax like:
`hypergraph update 9413d335997fe0ba0656c384d8be58e818324d7da5b114a4c7f0d4c7acd6aadf --parent c0245adafbc838bfbad808e6be3ab322c2746416637a15ebdbe79e4017b2fcb8` 
or `hypergraph update 9413d335997fe0ba0656c384d8be58e818324d7da5b114a4c7f0d4c7acd6aadf -p` 
works like 
`hypergraph update 9413d335997fe0ba0656c384d8be58e818324d7da5b114a4c7f0d4c7acd6aadf parents c0245adafbc838bfbad808e6be3ab322c2746416637a15ebdbe79e4017b2fcb8` 
- The five flags below and their shorthand aliases should all work with the `update` action

**Background**
Right now, these flags
```
    --title, -t                A content module's title
    --name, -n                 A profile module's name
    --subtype, -s              A content module's subtype
    --description, -d          Module description
    --parent, -p               Module parent(s)
```
can only be used for creating a new module, but not for updating a module's metadata.

**History**
- 2020/02/26: `read` was initially part of this issue, but was later scoped out

**Comment by juliangruber** [comment]
Closed through https://github.com/hypergraph-xyz/cli/pull/100
