### ISSUE TITLE
Better explanation of flags

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#88]
Right now, I would expect to be able to use the flags on `update` and `read`, which isn't possible. Also, the `[key]` `[key value]` syntax could do with a little more explaining, although this will change with #87.

Some examples of `create`, `read` and `update` would be nice.

And it would be good to specify that `subtype` requires a WikiData identifier, rather than any string.

**Comment by jameslibscie** [comment]
@juliangruber I don't see an update to the readme at https://github.com/hypergraph-xyz/cli. Is it correct that only the in-app part of this issue is done?

**Comment by juliangruber** [comment]
sorry about that, fixed
