### ISSUE TITLE
Update to + implement sdk 0.5.1

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/cli#90]
Contains:
- Update: mention cancelable promise
- Update: makes clone method cancelable + watch is an option + fixes
- Update: watch is false for most tests + cancel clone test
- Update: adjustments to be compat with in memory hyperswarm
- Update: add p-cancelable dep, use corestore-swarm-networking from github branch

See also [@p2pcommons/sdk#91](https://github.com/p2pcommons/sdk-js/pull/91)

**Comment by jameslibscie** [comment]
@juliangruber These are all quite technical. If there are product decisions to be made, let me know and I can give you a hand :)

**Comment by juliangruber** [comment]
No product decisions necessary :)
